# apiVersion: v1
# kind: Namespace
# metadata:
#   name: demo
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: kafka-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: '/var/log/kafka'
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: kafka-pv-claim
#   namespace: demo
# spec:
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-system
  labels:
    app: kafka-app
  namespace: demo
spec:
  clusterIP: None
  ports:
    - name: '9092'
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-system
  labels:
    app: kafka-app
  namespace: demo
spec:
  serviceName: kafka-system
  replicas: 3
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
        - name: kafka-container
          image: raihankhanraka/kafka-kraft:3.2.3
          ports:
            - containerPort: 9092
            - containerPort: 9093
#          env:
#            - name: REPLICAS
#              value: '3'
#            - name: SERVICE
#              value: kafka-svc
#            - name: NAMESPACE
#              value: demo
#            - name: DATA_DIR
#              value: /var/log/kafka
#            - name: CLUSTER_ID
#              value: bHNqbGZqZmxqbGpoaWhrCg==
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/log/kafka
            - name: config
              mountPath: /opt/kafka/serverconfig
      volumes:
        - name: config
          secret:
            secretName: kafka-system-config
            items:
              - key: "config.properties"
                path: "config.properties"
  volumeClaimTemplates:
  - metadata:
      name: kafka-storage
    spec:
      storageClassName: "standard"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
       

